
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Jmxproxybeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-jmxproxybeat>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-jmxproxybeat]]
== Jmxproxybeat Fields

Jmxproxybeat fields.



[float]
== bean Fields

Contains metrics from JMX bean.



[float]
=== bean.name

type: keyword

Name of the Bean which is retrieved.


[float]
=== bean.hostname

type: keyword

The hostname of JVM from which metrics are retrieved.


[float]
=== bean.attribute

type: keyword

The name of requested attribute.


[float]
=== bean.value

type: float

Value of the attribute.


