
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Jmxproxybeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-jmxproxybeat>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-jmxproxybeat]]
== Jmxproxybeat Fields

Jmxproxybeat fields.



[float]
== bean Fields

Contains metrics from JMX bean.



[float]
=== bean.name

type: keyword

Name of the Bean which is retrieved.


[float]
=== bean.hostname

type: keyword

The hostname of JVM from which metrics are retrieved.


[float]
=== bean.attribute

type: keyword

The name of requested attribute.


[float]
=== bean.value

type: float

Value of the attribute.


